### ISSUE TITLE
FindInBase/Parent/Child Attribute

### ISSUE THREAD

**Issue by OpOpYaDev** [uurha/BetterValidation#1]
Attributes are needed, which make it possible to automatically find the first link on the object itself, and on its parents/children.

One attribute with options, and 3 wrappers without options

- [ ] #2
- [ ] #3
- [ ] #4

Options:
- Only if field is empty / Only on validation.
- Options for depth (int)

**Comment by uurha** [comment]
- [ ] FindInBase
- [ ] Parent
- [ ] Child

Only if field is empty
